package main;
import entities.*;
import relations.*;
import entityLists.*;
import relationLists.*;

public class Global {
	public static AmmoList ammoList = new AmmoList();
	public static ArmorList armorList = new ArmorList();
	public static BackpackList backpackList = new BackpackList();
	public static BoosterList boosterList = new BoosterList();
	public static ClothingList clothingList = new ClothingList();
	//public static HealingItemList healingItemList = new HealingItemList();
	//public static ItemList itemList = new ItemList();
	public static MapList mapList = new MapList();
	public static PlayerList playerList = new PlayerList();
	public static SessionList sessionList = new SessionList();
	public static StandardList standardList = new StandardList();
	public static ThrowAbleList throwAbleList = new ThrowAbleList();
	public static VehicleList vehicleList = new VehicleList();
	public static WeaponList weaponList = new WeaponList();
	
	public static HappensOnList happensOnList = new HappensOnList();
	public static HasList hasList = new HasList();
	public static PlaysInList playsInList = new PlaysInList();
	public static SpawnsOnItemList spawnsOnItemList = new SpawnsOnItemList();
	public static SpawnsOnVehicleList spawnsOnVehicleList = new SpawnsOnVehicleList();
	
	public static void init() {
		//Ammo
		ammoList.getList().clear();
		Ammo ammo1 = new Ammo("5.56", "5.56", 100);
		ammoList.getList().add(ammo1);
		Ammo ammo2 = new Ammo("5.56", "5.56", 60);
		ammoList.getList().add(ammo2);
		Ammo ammo3 = new Ammo("7.62", "7.62", 100);
		ammoList.getList().add(ammo3);
		Ammo ammo4 = new Ammo("7.62", "7.62", 60);
		ammoList.getList().add(ammo4);
		Ammo ammo5 = new Ammo("9", "9", 100);
		ammoList.getList().add(ammo5);
		Ammo ammo6 = new Ammo("9", "9", 60);
		ammoList.getList().add(ammo6);
		Ammo ammo7 = new Ammo(".45", ".45", 100);
		ammoList.getList().add(ammo7);
		Ammo ammo8 = new Ammo(".45", ".45", 60);
		ammoList.getList().add(ammo8);
		Ammo ammo9 = new Ammo("12 Gauge", "12 Gauge", 30);
		ammoList.getList().add(ammo9);
		Ammo ammo10 = new Ammo("12 Gauge", "12 Gauge", 15);
		ammoList.getList().add(ammo10);
		Ammo ammo11 = new Ammo("5.56", "5.56", 160);
		ammoList.getList().add(ammo11);
		Ammo ammo12 = new Ammo("7.62", "7.62", 200);
		ammoList.getList().add(ammo12);
		Ammo ammo13 = new Ammo(".45", ".45", 420);
		ammoList.getList().add(ammo13);
		Ammo ammo14 = new Ammo("9", "9", 200);
		ammoList.getList().add(ammo14);
		Ammo ammo15 = new Ammo("12 Gauge", "12 Gauge", 60);
		ammoList.getList().add(ammo15);
		ammoList.exportJSON();
		
		//Armor
		armorList.getList().clear();
		Armor armor1 = new Armor("Motorcycle Helmet", "Head", 80, 80, 1);
		armorList.getList().add(armor1);
		Armor armor2 = new Armor("Military Helmet", "Head", 150, 150, 2);
		armorList.getList().add(armor2);
		Armor armor3 = new Armor("Spetsnaz Helmet", "Head", 230, 230, 3);
		armorList.getList().add(armor3);
		Armor armor4 = new Armor("Police Vest", "Chest", 200, 200, 1);
		armorList.getList().add(armor4);
		Armor armor5 = new Armor("Police Vest", "Chest", 220, 220, 2);
		armorList.getList().add(armor5);
		Armor armor6 = new Armor("Military Vest", "Chest", 250, 250, 3);
		armorList.getList().add(armor6);
		Armor armor7 = new Armor("Motorcycle Helmet", "Head", 80, 15, 1);
		armorList.getList().add(armor7);
		Armor armor8 = new Armor("Military Helmet", "Head", 150, 100, 2);
		armorList.getList().add(armor8);
		Armor armor9 = new Armor("Spetsnaz Helmet", "Head", 230, 50, 3);
		armorList.getList().add(armor9);
		Armor armor10 = new Armor("Police Vest", "Chest", 200, 80, 1);
		armorList.getList().add(armor10);
		Armor armor11 = new Armor("Police Vest", "Chest", 220, 90, 2);
		armorList.getList().add(armor11);
		Armor armor12 = new Armor("Military Vest", "Chest", 250, 200, 3);
		armorList.getList().add(armor12);
		armorList.exportJSON();
		
		//Backpack
		backpackList.getList().clear();
		Backpack backpack1 = new Backpack("Backpack", 150);
		backpackList.getList().add(backpack1);
		Backpack backpack2 = new Backpack("Backpack", 200);
		backpackList.getList().add(backpack2);
		Backpack backpack3 = new Backpack("Backpack", 250);
		backpackList.getList().add(backpack3);
		Backpack backpack4 = new Backpack("Utility Belt", 50);
		backpackList.getList().add(backpack4);
		backpackList.exportJSON();
		
		//Booster
		boosterList.getList().clear();
		Booster booster1 = new Booster("Adrenaline Syringe", 50, 100);
		boosterList.getList().add(booster1);
		Booster booster2 = new Booster("Painkiller", 30, 60);
		boosterList.getList().add(booster2);
		Booster booster3 = new Booster("Energy Drink", 20, 40);
		boosterList.getList().add(booster3);
		boosterList.exportJSON();
		
		//Clothing
		clothingList.getList().clear();
		Clothing clothing1 = new Clothing("Tracksuit Top (Yellow)", "Outer");
		clothingList.getList().add(clothing1);
		Clothing clothing2 = new Clothing("Tracksuit Pants (Yellow)", "Legs");
		clothingList.getList().add(clothing2);
		Clothing clothing3 = new Clothing("Baggy Pants (Black)", "Legs");
		clothingList.getList().add(clothing3);
		Clothing clothing4 = new Clothing("Coat", "Outer");
		clothingList.getList().add(clothing4);
		Clothing clothing5 = new Clothing("Long Sleeved Turtleneck (Black)", "Torso");
		clothingList.getList().add(clothing5);
		Clothing clothing6 = new Clothing("Zest Sunglasses", "Eyes");
		clothingList.getList().add(clothing6);
		Clothing clothing7 = new Clothing("Camo Hotpants", "Legs");
		clothingList.getList().add(clothing7);
		Clothing clothing8 = new Clothing("Punk Knuckle Gloves", "Hands");
		clothingList.getList().add(clothing8);
		Clothing clothing9 = new Clothing("Bloody Sneakers", "Feet");
		clothingList.getList().add(clothing9);
		Clothing clothing10 = new Clothing("Cropped Corset", "Torso");
		clothingList.getList().add(clothing10);
		Clothing clothing11 = new Clothing("Aviator Sunglasses", "Eyes");
		clothingList.getList().add(clothing11);
		Clothing clothing12 = new Clothing("Zest Bootcut Pants", "Legs");
		clothingList.getList().add(clothing12);
		Clothing clothing13 = new Clothing("Camo Cap)", "Head");
		clothingList.getList().add(clothing13);
		Clothing clothing14 = new Clothing("Vintage Gas Mask", "Mask");
		clothingList.getList().add(clothing14);
		Clothing clothing15 = new Clothing("Zest Loafers with Socks", "Feet");
		clothingList.getList().add(clothing15);
		Clothing clothing16 = new Clothing("Military Cap (Black))", "Head");
		clothingList.getList().add(clothing16);
		Clothing clothing17 = new Clothing("Ballistic Mask", "Mask");
		clothingList.getList().add(clothing17);
		Clothing clothing18 = new Clothing("School Shirt with Necktie", "Torso");
		clothingList.getList().add(clothing18);
		Clothing clothing19 = new Clothing("Mini-skirt (Purple)", "Legs");
		clothingList.getList().add(clothing19);
		clothingList.exportJSON();
		
		//Map
		mapList.getList().clear();
		Map map1 = new Map("Erangel", 64);
		mapList.getList().add(map1);
		Map map2 = new Map("Miramar", 64);
		mapList.getList().add(map2);
		Map map3 = new Map("Savage", 16);
		mapList.getList().add(map3);
		mapList.exportJSON();
		
		//Standard
		standardList.getList().clear();
		Standard standard1 = new Standard("Med Kit", 3, 1);
		standardList.getList().add(standard1);
		Standard standard2 = new Standard("Med Kit", 3, 2);
		standardList.getList().add(standard2);
		Standard standard3 = new Standard("First Aid Kit", 2, 3);
		standardList.getList().add(standard3);
		Standard standard4 = new Standard("First Aid Kit", 2, 1);
		standardList.getList().add(standard4);
		Standard standard5 = new Standard("Bandage", 1, 20);
		standardList.getList().add(standard5);
		Standard standard6 = new Standard("Bandage", 1, 10);
		standardList.getList().add(standard6);
		standardList.exportJSON();
		
		//ThrowAble
		throwAbleList.getList().clear();
		ThrowAble throwAble1 = new ThrowAble("Frag Grenade", "Damage", 100, 3);
		throwAbleList.getList().add(throwAble1);
		ThrowAble throwAble2 = new ThrowAble("Frag Grenade", "Damage", 100, 1);
		throwAbleList.getList().add(throwAble2);
		ThrowAble throwAble3 = new ThrowAble("Molotov Cocktail", "Damage", 100, 3);
		throwAbleList.getList().add(throwAble3);
		ThrowAble throwAble4 = new ThrowAble("Molotov Cocktail", "Damage", 100, 2);
		throwAbleList.getList().add(throwAble4);
		ThrowAble throwAble5 = new ThrowAble("Smoke Grenade", "Tactical", 0, 3);
		throwAbleList.getList().add(throwAble5);
		ThrowAble throwAble6 = new ThrowAble("Smoke Grenade", "Tactical", 0, 1);
		throwAbleList.getList().add(throwAble6);
		ThrowAble throwAble7 = new ThrowAble("Stun Grenade", "Tactical", 0, 1);
		throwAbleList.getList().add(throwAble7);
		ThrowAble throwAble8 = new ThrowAble("Stun Grenade", "Tactical", 0, 2);
		throwAbleList.getList().add(throwAble8);
		throwAbleList.exportJSON();
		
		//Vehicle
		vehicleList.getList().clear();
		Vehicle vehicle1 = new Vehicle("UAZ", 4, 100, 120);
		vehicleList.getList().add(vehicle1);
		Vehicle vehicle2 = new Vehicle("UAZ", 4, 50, 120);
		vehicleList.getList().add(vehicle2);
		Vehicle vehicle3 = new Vehicle("Dacia", 4, 100, 100);
		vehicleList.getList().add(vehicle3);
		Vehicle vehicle4 = new Vehicle("Dacia", 4, 75, 100);
		vehicleList.getList().add(vehicle4);
		Vehicle vehicle5 = new Vehicle("Bike", 2, 100, 150);
		vehicleList.getList().add(vehicle5);
		Vehicle vehicle6 = new Vehicle("Bike", 2, 69, 150);
		vehicleList.getList().add(vehicle6);
		Vehicle vehicle7 = new Vehicle("Bus", 6, 100, 50);
		vehicleList.getList().add(vehicle7);
		Vehicle vehicle8 = new Vehicle("Bus", 6, 25, 50);
		vehicleList.getList().add(vehicle8);
		Vehicle vehicle9 = new Vehicle("Truck", 4, 100, 100);
		vehicleList.getList().add(vehicle9);
		Vehicle vehicle10 = new Vehicle("Truck", 4, 40, 100);
		vehicleList.getList().add(vehicle10);
		Vehicle vehicle11 = new Vehicle("Buggy", 2, 100, 100);
		vehicleList.getList().add(vehicle11);
		Vehicle vehicle12 = new Vehicle("Buggy", 2, 70, 100);
		vehicleList.getList().add(vehicle12);
		vehicleList.exportJSON();
		
		//Weapon
		weaponList.getList().clear();
		Weapon weapon1 = new Weapon("M416", "Assault Rifle", 880, 698, 41, 30, 40);
		weaponList.getList().add(weapon1);
		Weapon weapon2 = new Weapon("SCAR-L", "Assault Rifle", 870, 625, 41, 30, 40);
		weaponList.getList().add(weapon2);
		Weapon weapon3 = new Weapon("M16A4", "Assault Rifle", 900, 800, 41, 30, 40);
		weaponList.getList().add(weapon3);
		Weapon weapon4 = new Weapon("GROZA", "Assault Rifle", 715, 750, 48, 30, 40);
		weaponList.getList().add(weapon4);
		Weapon weapon5 = new Weapon("AKM", "Assault Rifle", 715, 600, 48, 30, 40);
		weaponList.getList().add(weapon5);
		Weapon weapon6 = new Weapon("Micro Peen", "Submachine Gun", 350, 1250, 23, 25, 35);
		weaponList.getList().add(weapon6);
		Weapon weapon7 = new Weapon("UMP9", "Submachine Gun", 400, 652, 35, 30, 40);
		weaponList.getList().add(weapon7);
		Weapon weapon8 = new Weapon("Vector", "Submachine Gun", 300, 1090, 31, 13, 25);
		weaponList.getList().add(weapon8);
		Weapon weapon9 = new Weapon("Tommy Gun", "Submachine Gun", 280, 698, 38, 20, 50);
		weaponList.getList().add(weapon9);
		Weapon weapon10 = new Weapon("P18C", "Pistol", 375, 1000, 19, 17, 30);
		weaponList.getList().add(weapon10);
		Weapon weapon11 = new Weapon("P92", "Pistol", 380, 444, 29, 15, 20);
		weaponList.getList().add(weapon11);
		Weapon weapon12 = new Weapon("P1911", "Pistol", 250, 545, 35, 7, 15);
		weaponList.getList().add(weapon12);
		Weapon weapon13 = new Weapon("P1895", "Pistol", 330, 150, 46, 7, 7);
		weaponList.getList().add(weapon13);
		Weapon weapon14 = new Weapon("S696", "Shotgun", 370, 300, 25, 2, 2);
		weaponList.getList().add(weapon14);
		Weapon weapon15 = new Weapon("S1897", "Shotgun", 360, 80, 25, 5, 5);
		weaponList.getList().add(weapon15);
		Weapon weapon16 = new Weapon("S12K", "Shotgun", 350, 240, 22, 5, 10);
		weaponList.getList().add(weapon16);
		Weapon weapon17 = new Weapon("Mini14", "Sniper Rifle", 990, 600, 44, 20, 30);
		weaponList.getList().add(weapon17);
		Weapon weapon18 = new Weapon("SKS", "Sniper Rifle", 800, 666, 55, 10, 20);
		weaponList.getList().add(weapon18);
		Weapon weapon19 = new Weapon("KAR98K", "Sniper Rifle", 760, 32, 72, 5, 5);
		weaponList.getList().add(weapon19);
		Weapon weapon20 = new Weapon("VSS", "Sniper Rifle", 330, 698, 38, 10, 10);
		weaponList.getList().add(weapon20);
		Weapon weapon21 = new Weapon("Winchester", "Sniper Rifle", 760, 50, 72, 8, 8);
        weaponList.getList().add(weapon21);
        Weapon weapon22 = new Weapon("Dp-28", "Lightmachine Gun", 715, 600, 49, 47, 47);
        weaponList.getList().add(weapon22);
		weaponList.exportJSON();
		
		//Session
		sessionList.getList().clear();
		Session session1 = new Session("Game 1", "Server 1", "Squads", 1, 90, 1);
		sessionList.getList().add(session1);
		Session session2 = new Session("Game 2", "Server 2", "Dou", 5, 46, 10);
		sessionList.getList().add(session2);
		Session session3 = new Session("Game 3", "Server 3", "Solo", 10, 3, 30);
		sessionList.getList().add(session3);
		sessionList.exportJSON();
		
		//Player
		playerList.getList().clear();
		Player player1 = new Player("ChinaNumba1", "Male", 100, 0);
		playerList.getList().add(player1);
		Player player2 = new Player("PochinkiIsMyCity", "Female", 20, 50);
		playerList.getList().add(player2);
		Player player3 = new Player("CaoNiMa", "Male", 75, 0);
		playerList.getList().add(player3);
		Player player4 = new Player("Shroud", "Male", 100, 100);
		playerList.getList().add(player4);
		Player player5 = new Player("DrDisrespect", "Male", 100, 50);
		playerList.getList().add(player5);
		Player player6 = new Player("Grill", "Female", 80, 10);
		playerList.getList().add(player6);
		Player player7 = new Player("DontPanMe", "Female", 0, 0);
		playerList.getList().add(player7);
		Player player8 = new Player("CrateChaser420", "Male", 25, 50);
		playerList.getList().add(player8);
		playerList.exportJSON();
		
		//HappensOn
		happensOnList.getList().clear();
		HappensOn happensOn1 = new HappensOn(map1, session1);
		happensOnList.getList().add(happensOn1);
		HappensOn happensOn2 = new HappensOn(map2, session3);
		happensOnList.getList().add(happensOn2);
		HappensOn happensOn3 = new HappensOn(map3, session2);
		happensOnList.getList().add(happensOn3);
		happensOnList.exportJSON();
		
		//PlaysIn
		playsInList.getList().clear();
		PlaysIn playsIn1 = new PlaysIn(player1, session1);
		playsInList.getList().add(playsIn1);
		PlaysIn playsIn2 = new PlaysIn(player2, session1);
		playsInList.getList().add(playsIn2);
		PlaysIn playsIn3 = new PlaysIn(player3, session1);
		playsInList.getList().add(playsIn3);
		PlaysIn playsIn4 = new PlaysIn(player4, session1);
		playsInList.getList().add(playsIn4);
		PlaysIn playsIn5 = new PlaysIn(player5, session1);
		playsInList.getList().add(playsIn5);
		PlaysIn playsIn6 = new PlaysIn(player6, session1);
		playsInList.getList().add(playsIn6);
		PlaysIn playsIn7 = new PlaysIn(player7, session1);
		playsInList.getList().add(playsIn7);
		PlaysIn playsIn8 = new PlaysIn(player8, session1);
		playsInList.getList().add(playsIn8);
		playsInList.exportJSON();
		
		//SpawnsOnVehicle
		spawnsOnVehicleList.getList().clear();
		SpawnsOnVehicle sov1 = new SpawnsOnVehicle(vehicle1, map1);
		spawnsOnVehicleList.getList().add(sov1);
		SpawnsOnVehicle sov2 = new SpawnsOnVehicle(vehicle2, map1);
		spawnsOnVehicleList.getList().add(sov2);
		SpawnsOnVehicle sov3 = new SpawnsOnVehicle(vehicle3, map1);
		spawnsOnVehicleList.getList().add(sov3);
		SpawnsOnVehicle sov4 = new SpawnsOnVehicle(vehicle4, map1);
		spawnsOnVehicleList.getList().add(sov4);
		SpawnsOnVehicle sov5 = new SpawnsOnVehicle(vehicle5, map1);
		spawnsOnVehicleList.getList().add(sov5);
		SpawnsOnVehicle sov6 = new SpawnsOnVehicle(vehicle6, map1);
		spawnsOnVehicleList.getList().add(sov6);
		SpawnsOnVehicle sov7 = new SpawnsOnVehicle(vehicle7, map2);
		spawnsOnVehicleList.getList().add(sov7);
		SpawnsOnVehicle sov8 = new SpawnsOnVehicle(vehicle8, map2);
		spawnsOnVehicleList.getList().add(sov8);
		SpawnsOnVehicle sov9 = new SpawnsOnVehicle(vehicle9, map2);
		spawnsOnVehicleList.getList().add(sov9);
		SpawnsOnVehicle sov10 = new SpawnsOnVehicle(vehicle10, map2);
		spawnsOnVehicleList.getList().add(sov10);
		SpawnsOnVehicle sov11 = new SpawnsOnVehicle(vehicle11, map2);
		spawnsOnVehicleList.getList().add(sov11);
		SpawnsOnVehicle sov12 = new SpawnsOnVehicle(vehicle12, map2);
		spawnsOnVehicleList.getList().add(sov12);
		spawnsOnVehicleList.exportJSON();
		
		//SpawnsOnItem
		spawnsOnItemList.getList().clear();
		SpawnsOnItem soi1 = new SpawnsOnItem(ammo1, map1);
		spawnsOnItemList.getList().add(soi1);
		SpawnsOnItem soi2 = new SpawnsOnItem(ammo2, map1);
		spawnsOnItemList.getList().add(soi2);
		SpawnsOnItem soi3 = new SpawnsOnItem(ammo3, map1);
        spawnsOnItemList.getList().add(soi3);
        SpawnsOnItem soi4 = new SpawnsOnItem(ammo4, map2);
        spawnsOnItemList.getList().add(soi4);
        SpawnsOnItem soi5 = new SpawnsOnItem(ammo5, map2);
        spawnsOnItemList.getList().add(soi5);
        SpawnsOnItem soi6 = new SpawnsOnItem(ammo6, map2);
        spawnsOnItemList.getList().add(soi6);
        SpawnsOnItem soi7 = new SpawnsOnItem(ammo7, map3);
        spawnsOnItemList.getList().add(soi7);
        SpawnsOnItem soi8 = new SpawnsOnItem(ammo8, map3);
        spawnsOnItemList.getList().add(soi8);
        SpawnsOnItem soi9 = new SpawnsOnItem(ammo9, map3);
        spawnsOnItemList.getList().add(soi9);
        SpawnsOnItem soi10 = new SpawnsOnItem(weapon22, map1);
        spawnsOnItemList.getList().add(soi10);
        SpawnsOnItem soi11 = new SpawnsOnItem(weapon12, map1);
        spawnsOnItemList.getList().add(soi11);
        SpawnsOnItem soi12 = new SpawnsOnItem(weapon4, map1);
        spawnsOnItemList.getList().add(soi12);
        SpawnsOnItem soi13 = new SpawnsOnItem(weapon4, map2);
        spawnsOnItemList.getList().add(soi13);
        SpawnsOnItem soi14 = new SpawnsOnItem(weapon21, map2);
        spawnsOnItemList.getList().add(soi14);
        SpawnsOnItem soi15 = new SpawnsOnItem(weapon5, map2);
        spawnsOnItemList.getList().add(soi15);
        SpawnsOnItem soi16 = new SpawnsOnItem(weapon1, map3);
        spawnsOnItemList.getList().add(soi16);
        SpawnsOnItem soi17 = new SpawnsOnItem(weapon2, map3);
        spawnsOnItemList.getList().add(soi17);
        SpawnsOnItem soi18 = new SpawnsOnItem(weapon3, map3);
        spawnsOnItemList.getList().add(soi18);
        SpawnsOnItem soi19 = new SpawnsOnItem(armor3, map1);
        spawnsOnItemList.getList().add(soi19);
        SpawnsOnItem soi20 = new SpawnsOnItem(armor4, map2);
        spawnsOnItemList.getList().add(soi20);
        SpawnsOnItem soi21 = new SpawnsOnItem(backpack1, map3);
        spawnsOnItemList.getList().add(soi21);
        SpawnsOnItem soi22 = new SpawnsOnItem(booster1, map1);
        spawnsOnItemList.getList().add(soi22);
        SpawnsOnItem soi23 = new SpawnsOnItem(booster1, map2);
        spawnsOnItemList.getList().add(soi23);
        SpawnsOnItem soi24 = new SpawnsOnItem(booster1, map3);
        spawnsOnItemList.getList().add(soi24);
        SpawnsOnItem soi25 = new SpawnsOnItem(throwAble2, map1);
        spawnsOnItemList.getList().add(soi25);
        SpawnsOnItem soi26 = new SpawnsOnItem(throwAble6, map2);
        spawnsOnItemList.getList().add(soi26);
        SpawnsOnItem soi27 = new SpawnsOnItem(standard1, map1);
        spawnsOnItemList.getList().add(soi27);
        SpawnsOnItem soi28 = new SpawnsOnItem(standard4, map2);
        spawnsOnItemList.getList().add(soi28);
        SpawnsOnItem soi29 = new SpawnsOnItem(standard6, map3);
        spawnsOnItemList.getList().add(soi29);
		spawnsOnItemList.exportJSON();
		
		//Has
		hasList.getList().clear();
		Has has1 = new Has(weapon2, player1);
		hasList.getList().add(has1);
		Has has2 = new Has(weapon16, player1);
        hasList.getList().add(has2);
        Has has3 = new Has(ammo1, player1);
        hasList.getList().add(has3);
        Has has4 = new Has(ammo9, player1);
        hasList.getList().add(has4);
        Has has5 = new Has(armor1, player1);
        hasList.getList().add(has5);
        Has has6 = new Has(armor4, player1);
        hasList.getList().add(has6);
        Has has7 = new Has(backpack3, player1);
        hasList.getList().add(has7);
        Has has8 = new Has(standard1, player1);
        hasList.getList().add(has8);
        Has has9 = new Has(booster1, player1);
        hasList.getList().add(has9);
        Has has10 = new Has(throwAble1, player1);
        hasList.getList().add(has10);
        Has has11 = new Has(clothing4, player1);
        hasList.getList().add(has11);
        Has has12 = new Has(clothing5, player1);
        hasList.getList().add(has12);
        Has has13 = new Has(clothing6, player1);
        hasList.getList().add(has13);
        Has has14 = new Has(weapon12, player7);
        hasList.getList().add(has14);
        Has has15 = new Has(weapon22, player7);
        hasList.getList().add(has15);
        Has has16 = new Has(ammo13, player7);
        hasList.getList().add(has16);
        Has has17 = new Has(armor3, player7);
        hasList.getList().add(has17);
        Has has18 = new Has(armor6, player7);
        hasList.getList().add(has18);
        Has has19 = new Has(backpack2, player7);
        hasList.getList().add(has19);
        Has has20 = new Has(standard5, player7);
        hasList.getList().add(has20);
        Has has21 = new Has(standard2, player7);
        hasList.getList().add(has21);
        Has has22 = new Has(booster3, player7);
        hasList.getList().add(has22);
        Has has23 = new Has(throwAble6, player7);
        hasList.getList().add(has23);
        Has has24 = new Has(clothing7, player7);
        hasList.getList().add(has24);
        Has has25 = new Has(clothing8, player7);
        hasList.getList().add(has25);
        Has has26 = new Has(clothing10, player7);
        hasList.getList().add(has26);
		hasList.exportJSON();
		
		Create.createDB();
		InsertDB.insertAmmo(ammoList);
		InsertDB.insertArmor(armorList);
		InsertDB.insertBackpack(backpackList);
		InsertDB.insertBooster(boosterList);
		InsertDB.insertClothing(clothingList);
		InsertDB.insertMap(mapList);
		InsertDB.insertPlayer(playerList);
		InsertDB.insertSession(sessionList);
		InsertDB.insertStandard(standardList);
		InsertDB.insertThrowable(throwAbleList);
		InsertDB.insertVehicle(vehicleList);
		InsertDB.insertWeapon(weaponList);
	}
}